### ISSUE TITLE
How to install and run icplayer

### ISSUE THREAD

**Issue by JinPhil** [icplayer/icplayer#132]
How do I run and install ic player and create my own content ?

**Comment by witekz** [comment]
All icplayer documentation is currently being slowly moved from icplayer.com to http://www.mauthor.com/doc/en/page/Player-development you will find build information in the latter. 
For creating your own content - you can use an on-line editor available at the minstructor.com for free - currently it allows you to export the created content as a SCORM package which includes the compiled icplayer version as well.
